### ISSUE TITLE
Menu editor - save changes

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#16]
I can't get the save changes to come active after making changes to the menus (I changed a link and moved up the menu item)
![capture2](https://cloud.githubusercontent.com/assets/11847651/11333748/0340d79e-91c8-11e5-8a0b-5f197582ebbb.JPG)

**Comment by mikebattye** [comment]
I've had another look at this and Save comes up correctly if you make changes to links but not if you just move menus. Slightly confusing but not a major issue - ignore it if you want.

**Comment by asimshah** [comment]
I think that I said in some previous email that I had made individual (unique) changes to the login forms so that the "Save" button comes up without the need to edit some element.
This is one of the (many) improvements I made to the forms system before starting the booking app. This means that the booking app form buttons should work as we now expect (as well as the various login system forms) but the membership and the designer forms are the old type and have not been modified. At some point, perhaps, I will replace the forms system in these two apps with the one that is the booking app. But given that only you will ever use the membership and the designer apps (??!) I don't know if I will get round to it.
