### ISSUE TITLE
Login - Microsoft Edge

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#19]
There is a small issue when logging in with ME. Clicking Login on the menu brings up the login box briefly then it disappears. You have to click Login again to use the box.

Doesn't happen with Chrome.

**Comment by asimshah** [comment]
I don't see this behaviour using Edge.

**Comment by asimshah** [comment]
Please help me to reproduce this

**Comment by mikebattye** [comment]
Try this sequence in Edge or Chrome:

- Start a new session
- Go to dwh.test.webframe.co.uk
- Select go straight to 'online booking' in new left panel. (In Edge the login box briefly flashes here)
- Select login on the booking page.

It take me to a this page http://dwh.test.webframe.co.uk/#. No idea what the # stands for.
I am able to go through this sequence multiple times in the same session. The only way I can get out of the loop is to login through the top menu option.

**Comment by asimshah** [comment]
I can reproduce this now. It is definitely a bug but quite an obscure one. The relevant part of the code was written more than 18 months ago and quite a lot of other parts have now changed a lot so the cause is not immediately obvious. It will take some time to get to the bottom of. I expect the registration link next to the login link may well also be problematic.
On the other hand, can we ask if these links are actually required - can I remove them? If so, the visitor would have to return to the home page and login first. In any case, do plan to provide a link to booking if the visitor has not yet logged in?

**Comment by asimshah** [comment]
I have modified the login url, so it should now work. By the way you have already raised this under booking-app issues.

**Comment by mikebattye** [comment]
Yes it is fixed. However I notice that it takes you to your home page after login rather than staying in the booking app. The latter would be logical but I understand if it is too much of a faf to change.

**Comment by asimshah** [comment]
Actually that is deliberate. You might have a different home page for a particular user and want to make sue that they have seen whatever is on it.
But I agree that it will not be simple ...
