### ISSUE TITLE
Workflow: Access to Designer, etc.

### ISSUE THREAD

**Issue by mikebattye** [asimshah/webframe-issues#7]
Thinking about switching to various editing tools.
HTML is straightforward - black bar at top.
You could leave a link to designer as you have done in the left panel of alpha. Alternatively, you could save the url ../designer as a favourite. Similarly with Membership?

**Comment by asimshah** [comment]
I don't understand this comment at all.
All the tools are accessed using a url (/designer, /membership, etc.) - this was also the case in the previous version. The reason to do it this way remains the same: they are url and can therefore be edited into pages as hyperlinks. This allows any webframe site to choose whether to have any links that go to any of these tools (via hyperlinks or menu items). Given that you can control who has access to a page, you can therefore design it they way that suits you.
The HTML editing is different because you are not going to a separate tool (as before) but choosing to edit the page you are currently looking at - hence the need for a way to enter edit mode (the black bar at the top is the current method for doing this.
